render(input = "Code/06-table-02.Rmd", output_dir = "Outputs/Tables/")
render(input = "Code/06-table-03.Rmd", output_dir = "Outputs/Tables/")
render(input = "Code/06-table-04.Rmd", output_dir = "Outputs/Tables/")
render(input = "Code/06-table-05.Rmd", output_dir = "Outputs/Tables/")
render(input = "Code/06-table-06.Rmd", output_dir = "Outputs/Tables/")
